files:
  - source: /src/GitHub.Resources/Resources.resx
    translation: /%original_path%/Resources.%locale%.resx
  - source: /src/GitHub.VisualStudio/xlf/GitHub.VisualStudio.zh-CN.xlf
    translation: /**/GitHub.VisualStudio.%locale%.xlf
    dest: /GitHub.VisualStudio.xlf
